name: SuperBonus
version: 1.0
main: me.server.bonus.Main
api-version: 1.16
commands:
  bonus:
    description: Открыть меню наград для игроков
  lefttime:
    description: Команда для проверки (админ-панель)
    permission: bonus.admin
