name: SuperBonus
version: 1.0
main: me.server.bonus.Main
api-version: 1.16
commands:
  bonus:
    description: Открыть меню наград
  lefttime:
    description: Проверка времени (для админов)
    permission: bonus.admin
