name: Build Plugin 2026
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile and Package
        run: mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Bonus-Plugin-1.16.5
          path: target/bonus-1.0-SNAPSHOT.jar
